{% set name = "veros" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/veros-{{ version }}.tar.gz
  sha256: aed27091cedc25439fad12662bd1cea82e46f241cf1c02903da02eac4a1bcfbb

build:
  skip: true  # [py<=39]
  entry_points:
    - veros = veros.cli.veros:cli
    - veros-run = veros.cli.veros_run:cli
    - veros-copy-setup = veros.cli.veros_copy_setup:cli
    - veros-resubmit = veros.cli.veros_resubmit:cli
    - veros-create-mask = veros.cli.veros_create_mask:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=65.0.0
    - wheel
    - cython
    - pip
  run:
    - python
    - click <=8.1.8
    - entrypoints <=0.4
    - requests <=2.32.3,>=2.18
    - numpy <=2.2.2,>=1.13
    - scipy <=1.15.1
    - h5netcdf <=1.4.1
    - h5py <=3.12.1
    - pillow <=11.1.0
    - loguru <=0.7.3
    - tqdm <=4.67.1

test:
  imports:
    - veros
  commands:
    - pip check
    - veros --help
    - veros-run --help
    - veros-copy-setup --help
    - veros-resubmit --help
    - veros-create-mask --help
  requires:
    - pip

about:
  home: https://veros.readthedocs.io
  summary: The versatile ocean simulator, in pure Python, powered by JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
