{% set name = "veros" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/veros-{{ version }}.tar.gz
  sha256: b5ea3f767c8eb4acf9f6e528912fd40b44211ac03ac9a9fcc93fb4f8bca82995

build:
  skip: true  # [py<=39]
  entry_points:
    - veros = veros.cli.veros:cli
    - veros-run = veros.cli.veros_run:cli
    - veros-copy-setup = veros.cli.veros_copy_setup:cli
    - veros-resubmit = veros.cli.veros_resubmit:cli
    - veros-create-mask = veros.cli.veros_create_mask:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=65.0.0
    - wheel
    - cython
    - pip
  run:
    - python
    - click <=8.2.1
    - entrypoints <=0.4
    - requests <=2.32.4,>=2.18
    - numpy <=2.3.1,>=1.13
    - scipy <=1.16.0
    - h5netcdf <=1.6.3
    - h5py <=3.14.0
    - pillow <=11.3.0
    - loguru <=0.7.3
    - tqdm <=4.67.1

test:
  imports:
    - veros
  commands:
    - pip check
    - veros --help
    - veros-run --help
    - veros-copy-setup --help
    - veros-resubmit --help
    - veros-create-mask --help
  requires:
    - pip

about:
  home: https://veros.readthedocs.io
  summary: The versatile ocean simulator, in pure Python, powered by JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
