{% set name = "veros" %}
{% set version = "1.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/veros-{{ version }}.tar.gz
  sha256: 67cb1b8917b16c3df8fb0574c08b10be813546df9d9e6ec3475e864da26ec6c1

build:
  skip: true  # [py<38]
  entry_points:
    - veros = veros.cli.veros:cli
    - veros-run = veros.cli.veros_run:cli
    - veros-copy-setup = veros.cli.veros_copy_setup:cli
    - veros-resubmit = veros.cli.veros_resubmit:cli
    - veros-create-mask = veros.cli.veros_create_mask:cli
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=65.0.0
    - wheel
    - cython
    - pip
  run:
    - python
    - click <=8.1.7
    - entrypoints <=0.4
    - requests <=2.31.0,>=2.18
    - numpy <=1.26.0,>=1.13
    - scipy <=1.11.3
    - h5netcdf <=1.2.0
    - h5py <=3.10.0
    - pillow <=10.0.1
    - loguru <=0.7.2
    - tqdm <=4.66.1

test:
  imports:
    - veros
  commands:
    - pip check
    - veros --help
    - veros-run --help
    - veros-copy-setup --help
    - veros-resubmit --help
    - veros-create-mask --help
  requires:
    - pip

about:
  home: https://veros.readthedocs.io
  summary: The versatile ocean simulator, in pure Python, powered by JAX
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
